<?php

namespace Tests\Unit;

use App\Helpers\DateHelper;
use PHPUnit\Framework\TestCase;

/**
 * @package Tests
 * @group unit
 * @group ready
 */
class HelpersTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @dataProvider \Tests\unit\Provider\Helpers\DataProvider::provideWorkingDaysData
     */
    public function testGetNextWorkingDay($expected, $data)
    {
        $this->assertEquals(date("Y") . $expected, DateHelper::getNextWorkingDay(date("Y") . $data));
    }
}
